### PR TITLE
chore(icon): update icons package.json, remove svg folder

### PR DESCRIPTION
**Pull request by Jerd0**
- [x] Refactoring (old API is revised and supported)
- [x] Chore (updates to the build process or auxiliary tools and libraries)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Jerd0** [comment]
@leonid do you have any idea why alerts visual regression has failed?

**Comment by leonid** [comment]
> @leonid do you have any idea why alerts visual regression has failed?

Try to run it locally and you will see the difference, also if these are positive changes then you have to update snapshots by running: 
- 'generate test image' pnpm run cypress:docker:build
- 'run cypress tests' pnpm run cypress:docker:run

**Comment by leonid** [comment]
> @leonid do you have any idea why alerts visual regression has failed?

I think thats because icons are not working any more, and they are visually disappeared from snapshots

**Comment by Jerd0** [comment]
> > @leonid do you have any idea why alerts visual regression has failed?
> 
> I think thats because icons are not working any more, and they are visually disappeared from snapshots

image
It looks like it works now =), but in the previous version it didn't

**Review by leonid — APPROVED** [review]

**Pull request merged**
